# Generated by Django 2.2.2 on 2019-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190919_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='blog/%Y/%m/%D/')),
            ],
            options={
                'verbose_name': 'pdf',
            },
        ),
    ]
