# Generated by Django 2.2.2 on 2019-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/article/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='blog/pdf/%Y/%m/%D/'),
        ),
    ]
