# Generated by Django 2.2.6 on 2019-10-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='acti/produits/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='acti/produits/')),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acti.Produit')),
            ],
        ),
    ]
