# Generated by Django 2.2.6 on 2019-10-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementsFablab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='acti/produits/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Evenements',
            new_name='EvenementsCulturel',
        ),
        migrations.AlterField(
            model_name='carte',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acti.Produit'),
        ),
    ]
