# Generated by Django 2.2.6 on 2019-10-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acti', '0002_auto_20191017_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassBureaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Abonnements',
            new_name='AbonnementsFablab',
        ),
        migrations.DeleteModel(
            name='Carte',
        ),
    ]
