# Generated by Django 2.2.6 on 2019-10-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acti', '0003_auto_20191017_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passbureaux',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
