# Generated by Django 2.2.6 on 2019-10-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191017_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesionAssciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='adhesion',
            field=models.ForeignKey(default='usager', on_delete=django.db.models.deletion.CASCADE, to='home.AdhesionAssciation'),
        ),
        migrations.AddField(
            model_name='member',
            name='categorie',
            field=models.ForeignKey(default='acti', on_delete=django.db.models.deletion.CASCADE, to='home.Categorie'),
        ),
    ]
