# Generated by Django 2.2.6 on 2019-10-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191017_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesionassciation',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adhesionassciation',
            name='type',
            field=models.CharField(default='usager', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='adhesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AdhesionAssciation'),
        ),
    ]
